---
# Setup Grafana
- name: get all ip
  debug:
    var: ansible_all_ipv4_addresses

- name: get default ip
  debug: 
    var: ansible_default_ipv4.address

- name: Add Grafana repo
  apt_repository: 
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Add Grafana Key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Install Grafana
  apt: 
    update_cache: yes
    name: 
      - grafana
      - apt-transport-https
    state: present

- name: Copy grafana.ini file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Start Grafana
  systemd:
    name: grafana-server
    state: started
    daemon_reload: yes
    enabled: yes

- name: Allow intra net access to grafana
  iptables:
    chain: INPUT
    protocol: tcp
    source: 10.0.0.0/8
    destination_port: '3000'
    jump: ACCEPT

- name: Save iptables rules to /etc/sysconfig/iptables
  lineinfile:
    path: /etc/sysconfig/iptables
    line: '-A INPUT -s 10.0.0.0/8 -p tcp -m tcp --dport 3000 -j ACCEPT'
    


    
